version: '3.8'

services:
  nextjs-app:
    container_name: 'coffee_shop'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules # Tránh lỗi ghi đè node_modules từ máy host
    command: ['npm', 'start']
